module.exports = {
  likes: '{likes, number} me gusta',
  'logout': 'Salir',
  'english': 'Inglés',
  'spanish': 'Español',
  'signup.subheading': 'Regístrate para ver fotos de tus amigos estudiando en Platzi',
  'signup.facebook': 'Inicia sesión con facebook',
  'signup.text': ' Iniciar sesión',
  'email': 'Correo electrónico',
  'username': 'Nombre de usuario',
  'fullname': 'Nombre completo',
  'password': 'Contraseña',
  'signup.call-to-action': 'Registrate',
  'signup.have-account': '¿Tienes una cuanta?',
  'signin': 'Entrar',
  'signin.not-have-account': '¿No tienes una cuenta?',
  'language': 'Idioma',
  'upload': 'Subir',
  'upload-picture': ' Subir foto'
}